### ISSUE TITLE
Change global ggplot theme

### ISSUE THREAD

**Issue by AmeliaES** [AmeliaES/TIDAL#11]
Not urgent, but I've figured a way to edit the global default ggplot theme here:
https://github.com/AmeliaES/TIDAL/blob/3a3a00a124f7721bd2499f5c98b175aba3e9348a/inst/TIDALapp/app.R#L12-L14
I'm not sure the plots look particularly pretty... if you're bored feel free to have a look if you can make them look nicer :-)

**Comment by EileenYXu** [comment]
changed default colour palette to colourblind-friendly, not much else to add I guess to the plots but I've changed the backgrounds of the plots to transparent so if we want to implement an extra high-contrast mode we could have a black background and the plot should hopefully inherit that too without setting it manually. merged into main
