### ISSUE TITLE
[FEATURE] toggle dark/high contrast mode

### ISSUE THREAD

**Issue by EileenYXu** [AmeliaES/TIDAL#20]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AmeliaES** [comment]
https://stackoverflow.com/questions/70095322/dark-mode-switch-doesnt-work-using-navbarpage-shiny needed to change the code in navbar_page and specifically tell each fluid page what the theme was. 

https://github.com/AmeliaES/TIDAL/commit/27582f531f1903e60697ebd2374d348eba990db7

**Comment by AmeliaES** [comment]
https://github.com/AmeliaES/TIDAL/commit/135745940ef787c02db7397a89209e9fdc833b4d change UI for selecting theme
